### ISSUE TITLE
instance.table(t).column_family(f).gc_rule always returns None

### ISSUE THREAD

**Issue by czka** [googleapis/python-bigtable#17]
CentOS 7, Python 3.6.8, google-cloud-bigtable==1.2.1 (0.34.0 has the same issue, I haven't tried intermediate versions).

Example code to reproduce the issue. Try any table in any Bigtable cluster - this is 100% reproducible as far as I have checked:
```
from google.cloud import bigtable

p='some_project'; i='some_instance'; c='some_cluster';  t='some_table'

bigtable_client = bigtable.Client(project=p, admin=True)

instance = bigtable_client.instance(i)
instance.reload()

cluster = instance.cluster(c)
cluster.reload()

for f in instance.table(t).list_column_families():
  print(f, instance.table(t).column_family(f).gc_rule)
```
Output:
```
ACTION None
OTHER None
ACTING_USER None
ORGIN None
```

I'd rather expect the same output as with `cbt` below (I have used 0.9.0 6ab8d8ff here, but older ones used to work as well):
```
$ cbt -project some_project -instance some_instance ls some_table
Family Name	GC Policy
-----------	---------
ACTING_USER	versions() > 1
ACTION		versions() > 1
ORGIN		versions() > 1
OTHER		versions() > 1
```

If that's not a bug and `instance.table(t).column_family(f).gc_rule` is not supposed to return the actual GC policy, how else can I query it per table?

**Comment by HemangChothani** [comment]
@czka Code snippet to retrieve  `GC ploicy`

        for f, value in instance.table(t).list_column_families().items():
            print(f, value.gc_rule.to_pb())

**Comment by czka** [comment]
@HemangChothani Yup, that works. Thanks. So not a bug after all I guess.

**Comment by HemangChothani** [comment]
@czka  Ok, thanks, so closing this issue for now.
Yes, you can open the feature request, after discussion the responsible person will decide about.

**Comment by czka** [comment]
Why closing this ticket and telling me to open another one, instead of making it a feature request?

**Comment by HemangChothani** [comment]
As i found in the documentation,  [column family](https://google-cloud-python.readthedocs.io/en/0.32.0/bigtable/table.html#google.cloud.bigtable.table.Table.column_family) is used for create, update and delete operations not used for retrieval. As per my observation api or back-end doesn't support till which you are asking for.

Also you can can see here that list_column_families() method created the object of `column family` and then return.
https://github.com/googleapis/python-bigtable/blob/0134f2edfb0893260feaad31dec27cc5962914b7/google/cloud/bigtable/table.py#L438-L441

So if  you want you can edit description with specific requirements for the feature and reopen this issue, so i can ask the responsible person about feasibility of this feature.
