### ISSUE TITLE
Bigtable python client - memory leak in every requests

### ISSUE THREAD

**Issue by tojobac** [googleapis/python-bigtable#187]
#### Environment details
1. Google cloud bigtable
2. Ubuntu 18.04
3. python 3.7
4. google-cloud-bigtable==1.6.1

#### The issue
We have seen some memory leak in our python program that uses google-cloud-bigtable. It grows slower, but after a few days, our program consume all the memory of our VM. After investigating, we saw the memory leak occurs every time we make a bigtable request (read or write).
We saw some topics about Memory leak when people re create client every time they make a request. The solution offered was always to close the gRPC channel after each request or (better) using a single client. ie:

https://stackoverflow.com/questions/54371554/bigtable-grpc-memory-leak-how-to-resolve
https://github.com/googleapis/google-cloud-python/issues/7207

In our case we already use a single client but still have a memory leak.

#### Code example
To illustrate the issue, we made 2 tests and monitored the memory growth in 2 cases. 
1/ With a single client we make many read requests and monitor the memory
2/ We still make many read requests but each time we create a new client and at the end we explicitly close the grpc channel.

In both case, we still see that the memory still growing (memory leak)

**Test case 1**
```python
    def run_test(self, instance_id, json_credentials, table_id, row_key):
        client = Client.from_service_account_json(json_credentials)
        instance = Instance(instance_id, client)

        table = Table(table_id, instance)
        for i in range(2000):
            partial_row = table.read_row(row_key)
            sleep(0.05)
```
![image](https://user-images.githubusercontent.com/29761736/103223683-d590d600-4937-11eb-8c0d-4ddc8eaeff1e.png)

**Test case 2**
```
    def run_test_renew_client(self, instance_id, json_credentials, table_id, row_key):
        for i in range(2000):
            client = Client.from_service_account_json(json_credentials)
            instance = Instance(instance_id, client)

            table = Table(table_id, instance)
            partial_row = table.read_row(row_key)

            client.table_data_client.transport.channel.close()
            sleep(0.05)
```
![image](https://user-images.githubusercontent.com/29761736/103223725-df1a3e00-4937-11eb-83ea-189abc642ff1.png)

As you can see the memory grows slowly but still growing.

Thanks in advance!

**Comment by tseaver** [comment]
@tojobac Thank you for the detailed report.  I'm investigating using Python's `gc` module, and can't see any leakage at the Python level.  [This script](https://gist.github.com/tseaver/356682c2d5d0ca34eb5e487483efbf3d) produces the following output for me:

```
$ .nox/system-3-8/bin/python repro-187.py 
................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................

Before collection

Generation        Before     After      Delta
++++++++++        ++++++     ++++++     ++++++
        0:          338         504        166
        1:            2           8          6
        2:           10          10          0

After collection

Generation        Before     After      Delta
++++++++++        ++++++     ++++++     ++++++
        0:          338           0       -338
        1:            2           0         -2
        2:           10           0        -10
```


Can you try adding `import gc` at the top of your module, and then `gc.collect()` just after the `sleep` call?

If the memory growth stops at that point, then we might need to add some documentation describing how `gc` could be used in long-running scripts.

If the growth *does* continue, then we likely need to look into stuff at the lower level (`grpcio`), which does its own memory management outside of Python's garbage collection.

**Comment by tojobac** [comment]
@tseaver Thank replying
I tried calling gc.collect but the memory still grows. As you can see in this screenshot (I profile the app execution with PyVMonitor)
![untitled](https://user-images.githubusercontent.com/29761736/105465079-8bcfad00-5ca3-11eb-9a05-aa6fee7e18e2.png)

**Comment by tseaver** [comment]
@tojobac Seems like the leak might be in `grpcio`, then.  Can you please provide the output of `pip list` in the environment where you are measuring the leak?

**Comment by tojobac** [comment]
@tseaver 

> Package                  Version             Location                              
------------------------ ------------------- --------------------------------------
absl-py                  0.11.0              
astor                    0.8.1               
attrs                    20.3.0              
Automat                  20.2.0              
bcrypt                   3.2.0               
cachetools               4.2.0               
certifi                  2020.6.20           
cffi                     1.14.4              
chardet                  4.0.0               
click                    7.1.2               
configobj                5.0.6               
constantly               15.1.0              
cryptography             3.1.1               
Cython                   0.29.10             
elasticsearch            6.8.1               
emoji                    0.5.1               
faiss                    1.6.0               
faiss-gpu                1.6.0               
fasttext                 0.9.1               
Flask                    1.1.1               
gast                     0.4.0               
gevent                   20.9.0              
google-api-core          1.24.1              
google-auth              1.24.0              
google-cloud-bigtable    1.6.1               
google-cloud-core        1.5.0               
google-cloud-logging     1.11.0              
google-cloud-monitoring  0.31.1              
google-cloud-storage     1.16.1              
google-crc32c            1.1.0               
google-resumable-media   1.2.0               
googleapis-common-protos 1.52.0              
greenlet                 0.4.17              
grpc-google-iam-v1       0.12.3              
grpcio                   1.34.0              
h5py                     2.10.0              
hyperlink                20.0.1              
idna                     2.10                
importlib-metadata       3.3.0               
incremental              17.5.0              
intervaltree             3.0.2               
itsdangerous             1.1.0               
Jinja2                   2.11.2              
kazoo                    2.5.0               
Keras                    2.2.4               
Keras-Applications       1.0.6               
Keras-Preprocessing      1.0.5               
lz4                      2.1.6               
Markdown                 3.3.3               
MarkupSafe               1.1.1               
mkl-fft                  1.2.0               
mkl-random               1.1.1               
mkl-service              2.3.0               
mock                     4.0.3               
mockito                  1.1.1               
mysql-connector-python   8.0.12              
numpy                    1.19.2              
pandas                   0.25.3              
Pillow                   5.4.1               
pip                      20.0.2              
plotly                   4.14.1              
protobuf                 3.14.0              
pyasn1                   0.4.8               
pyasn1-modules           0.2.8               
pybind11                 2.2.4               
pycparser                2.20                
PyHamcrest               2.0.2               
pykafka                  2.8.0               
Pympler                  0.9                 
pyOpenSSL                19.1.0              
python-dateutil          2.8.1               
pytz                     2020.4              
PyYAML                   5.3.1               
requests                 2.25.1              
retrying                 1.3.3               
rsa                      4.6                 
schedule                 0.6.0               
scipy                    1.1.0               
service-identity         18.1.0              
setuptools               51.0.0.post20201207 
six                      1.15.0              
sortedcontainers         2.3.0               
stackimpact              1.2.7               
tabulate                 0.8.7               
tensorboard              1.13.1              
tensorflow               1.13.1              
tensorflow-estimator     1.13.0              
termcolor                1.1.0               
tqdm                     4.28.1              
Twisted                  20.3.0              
typing-extensions        3.7.4.3             
urllib3                  1.26.2              
Werkzeug                 1.0.1               
wheel                    0.36.2              
xxhash                   1.3.0               
yappi                    1.3.2               
zipp                     3.4.0               
zope.event               4.5.0               
zope.interface           5.2.0

**Comment by tojobac** [comment]
@tseaver any news?

**Comment by tseaver** [comment]
@tojobac Sorry, got pulled away.  That is a pretty recent version of `grpcio`, which eliminates one hypotheses:  there was a [leak fixed in version 1.30.0](https://github.com/grpc/grpc/issues/22851).

**Comment by tojobac** [comment]
@tseaver So do you have any idea about what could cause the leak in may case?

**Comment by tseaver** [comment]
@tojobac My script is reading an empty row:  can you describe the kind of data in the row you are reading?  Is it like the data in the linked StackOverflow issue?

@lidizheng do you know of any open leakage issues which could be in play here?

**Comment by tseaver** [comment]
I have updated my repro script to use the `psutil` module to capture RSS / USS for the process.  The output does seem to show the leak here:

```
$ .nox/unit-3-8/bin/python repro-187.py 

Before reads

RSS: 54,960,128
USS: 48,455,680

................................................................................
RSS: 55,726,080
USS: 49,098,752

................................................................................
RSS: 55,758,848
USS: 49,135,616

................................................................................
RSS: 55,767,040
USS: 49,143,808

................................................................................
RSS: 55,779,328
USS: 49,156,096

................................................................................
RSS: 55,791,616
USS: 49,168,384

................................................................................
RSS: 55,799,808
USS: 49,176,576

................................................................................
RSS: 55,812,096
USS: 49,188,864

................................................................................
RSS: 55,820,288
USS: 49,197,056

................................................................................
RSS: 55,955,456
USS: 49,213,440

................................................................................
RSS: 55,963,648
USS: 49,221,632

................................................................................
RSS: 55,971,840
USS: 49,229,824

................................................................................
RSS: 55,984,128
USS: 49,242,112

................................................................................
RSS: 55,996,416
USS: 49,258,496

................................................................................
RSS: 56,016,896
USS: 49,287,168

................................................................................
RSS: 56,025,088
USS: 49,299,456

................................................................................
RSS: 56,037,376
USS: 49,311,744

................................................................................
RSS: 56,045,568
USS: 49,319,936

................................................................................
RSS: 56,057,856
USS: 49,332,224

................................................................................
RSS: 56,066,048
USS: 49,340,416

................................................................................
RSS: 56,078,336
USS: 49,352,704

................................................................................
RSS: 56,086,528
USS: 49,360,896

................................................................................
RSS: 56,098,816
USS: 49,373,184

................................................................................
RSS: 56,107,008
USS: 49,381,376

................................................................................
RSS: 56,115,200
USS: 49,389,568

................................................................................
RSS: 56,119,296
USS: 49,393,664



Before collection

RSS: 56,119,296
USS: 49,393,664

Generation        Before     After      Delta
++++++++++        ++++++     ++++++     ++++++
        0:          383         523        140
        1:            9           3         -6
        2:            0           1          1

After collection

RSS: 56,119,296
USS: 49,393,664

Generation        Before     After      Delta
++++++++++        ++++++     ++++++     ++++++
        0:          383          22       -361
        1:            9           0         -9
        2:            0           0          0
```

**Comment by tojobac** [comment]
@tseaver 
> can you describe the kind of data in the row you are reading?

My data types are String, Datetime and numbers which are stored as Bytes.

> I have updated my repro script to use the psutil module to capture RSS / USS for the process. The output does seem to show the leak here

It seems that your new script shows the leak, may you have any idea of what could be the cause?

**Comment by lidizheng** [comment]
@tseaver  Sorry I missed the ping. I tried the reproduce script provided in https://github.com/googleapis/google-cloud-python/issues/7207. And I can reproduce some-level of memory leak (around 4 MB in 100 row writes, and the increase speed slows down). But by diffing the Python objects, there isn't anything stick out. So, there could be something leaking inside the gRPC Python extension.

```
                       types |   # objects |   total size
============================ | =========== | ============
                        list |        5956 |    597.59 KB
                         str |        6113 |    447.48 KB
                         int |        1426 |     39.08 KB
                        dict |          61 |     36.30 KB
                        type |          11 |     17.21 KB
                     weakref |          95 |      8.16 KB
                        code |          51 |      7.18 KB
                         set |          24 |      5.69 KB
                   frozenset |           6 |      5.36 KB
                 abc.ABCMeta |           4 |      5.29 KB
  builtin_function_or_method |          58 |      4.53 KB
         urllib.parse.Quoter |           1 |      2.26 KB
         function (__init__) |           8 |      1.12 KB
                    property |          10 |    880     B
           getset_descriptor |          10 |    800     B
```

(Full log: https://gist.github.com/lidizheng/84f17269c8d91f3dd837679cd2a77c75)
(Repro script: https://gist.github.com/lidizheng/061ef3b98edfb7d279c8f931b7fa574e) (Creating and closing channels at every run)

Interestingly, the leak between row writes are always a clean multiple of KBs (like 4KB, 116KB, 60KB).

@tojobac Do you know which behavior generates the most memory leak (row read or row write) (relative to data size)?

**Comment by lidizheng** [comment]
@tojobac

Suggestions from @sduskis in https://github.com/googleapis/google-cloud-python/issues/7207#issuecomment-483734529:

1. Use a single client;
2. Remove `admin=True`.

For the new experiment, I applied above updates, changed the platform to Linux, and hooked up our C extension with address sanitizer (commonly used to debug memory leak in C++). Within 20000 writes, the memory usage climbed from 339MB to ~475MB (first 300 writes), and stayed at ~475MB for the reset of the experiment: https://gist.github.com/lidizheng/9712c18a11f88955efa2d3b7c5e24c7a. (There is an ASAN warning about gRPC shutdown, but it not a memory leak.) (This experiment uses more memory because it's a debug build.)

Similar result can be found with 2000 writes on macOS with latest gRPC release (https://gist.github.com/lidizheng/cc1c05b982319d83c936a8b32197c49f) (60MB->61MB plateau after 200 writes).

This result indicates that there is no memory leak in Python or C/C++ extension if we use only one client.

I understand memory in Google Cloud Functions affects cost. Can you give the above two suggestions a try?

**Comment by tojobac** [comment]
@lidizheng @tseaver
Thank you for your answer.
First of all, in our production usage we already use only One client without admin True

I tried to monitor our code with you method and query the Same row key 2000 time. The memory grows a little some times (why?) but a little about 10Kb in all.
I change to code query a different row keys (so 2000 row keys) and the memory grows more frequently. At the end it grows ~ 1.20 Mb

Notes that in our production we have a process that get row keys from queue, query them then process the data. So the row keys change all the time. The process is suppose to treat tens millions to hundred millions different row keys/data per days, everyday.

In simple/small examples the growth seems to be little (just 1.2Mb for 2000 queries) but with our charge those "little" memory growth make the Virtual Machine crash (out of memory) after some days (million queries every day).

What I can see in examples (mine and yours) is that the memory only grows (sometimes/rarely decrease and little than when it grows). Something is accumulated.

I'd like to know did this bigtable client use some kind of cache (which is never released)? It may explain why memories spent increase more when we queries different data.

**Comment by lidizheng** [comment]
@tojobac From the gRPC Python view, we don't keep any cache or similar stuff for requests and responses. All per-call objects are bound to the RPC's lifecycle, same for the channel.

One corner case I can think of is channel trace events. I wonder if there is a lot of retry/reconnect/error happening? gRPC Core does keep a small trace event when the connectivity state of the channel changes. See [code](https://github.com/grpc/grpc/blob/7914aecf1bec0af45932cdcf1bca9a944a943311/src/core/lib/channel/channel_trace.h#L87). The channel trace events can be queried via Channelz service or [`grpcdebug`](https://github.com/grpc-ecosystem/grpcdebug). For this to consume lots of memory, we need to see millions of trace events.

On the other hand, can you help to instrument your deployment to print memory usage and Python object diffs? Here is one way I like to do it, feel free to use your methods.

It requires two external dependencies:

```shell
pip install -U pympler psutil
```

You can invoke the `print_memory()` function to print the actual used memory, virtual memory, and Python objects diff. This can happen periodically, or per-100-calls, or per-1000-calls, or give it a handler to be triggered via a request.

```python
import os
import gc
import psutil
from pympler import muppy, summary, tracker, classtracker

tr = tracker.SummaryTracker()
process = psutil.Process(os.getpid())
start_memory = process.memory_info()
last_memory = start_memory
print('Start Memory Usage:', start_memory)

def format_memory(name, used_memory, last_memory):
  diff_memory = used_memory - last_memory
  last_memory = used_memory
  print(name, ":", used_memory, "%.2fMB" % (used_memory/1024/1024), "%+.2f" % diff_memory, "%+.2fMB" % (diff_memory/1024/1024))

def print_memory():
  gc.collect()
  global last_memory
  current_memory = process.memory_info()
  format_memory('RSS', current_memory.rss, last_memory.rss)
  format_memory('VMS', current_memory.vms, last_memory.vms)
  last_memory = current_memory
  sum1 = tr.diff()
  summary.print_(sum1)
```

**Comment by tojobac** [comment]
@lidizheng Ok I'll try it, I will give a feedback ASAP :)

**Comment by tseaver** [comment]
@tojobac Please reopen / follow-up if you can provide more information.
