### ISSUE TITLE
Big Table Memory Leak - Read Rows / Consume All

### ISSUE THREAD

**Issue by alexgordonpandera** [googleapis/python-bigtable#25]
#### Environment details

**1. Specify the API at the beginning of the title (for example, "BigQuery: ...")**
    BigTable
**2. OS type and version**
  Container-Optimized OS from Google (GKE)
**3. Python version and virtual environment information: `python --version`**
    Python 3.6.5
**4. google-cloud-<service> version:  `pip show google-<service>` or `pip freeze`**
google-cloud-bigtable v1.2.1

#### Steps to reproduce / Bug Logical Reasoning

When deploying the micro service within GKE, the following code example will consume the memory of a pod until it reaches the limit of allocated memory value for the pod.  This behavior continues no matter the size of the memory limit.

It has been determined that read_job.consume_all() is the source of the memory leak due to the following logic:

The value that this function is returning is an empty dict.  Therefore, it can be confirmed that no code upstream from this function is causing the memory leak.  Tests have also been performed to remove the functionality and the observed memory leak was eliminated.  Therefore it is conclusive that the leak is apart of code example below.

To further pinpoint where the leak is occurring. When removing the read_job.consume_all() function, the memory issues cease to exist.  Thus concluding the bug resides within the consume_all functionality.

#### Code example
Full Function
```python
def multi_get_by_row_keys(row_keys, bt_table=FEATURES_TABLE):
    bt_table, client = get_client_table()
    row_keys = [
        format_row_key(row_key)
        for row_key in row_keys
    ]

    row_set = RowSet()
    for key in row_keys:
           row_set.add_row_key(key) 
    read_job = bt_table.read_rows(row_set=row_set)

    row_dict = {}
    read_job.consume_all()

    row_dict = read_job.rows

    read_job.cancel()
    close_client(client)
    del read_job
    del bt_table
    del client
    del row_set
    gc.collect()

    return {}
```

Perceived section causing Memory Leak 
```python
    read_job = bt_table.read_rows(row_set=row_set)

    row_dict = {}
    read_job.consume_all()

    row_dict = read_job.rows

    read_job.cancel()
    close_client(client)
```

#### Stack trace
No error logs occur. Pods are evicted as they consume more memory than allocated.

**Comment by danoscarmike** [comment]
@alexgordonpandera thanks for filing this issue. I have moved it here to the `python-bigtable` service-specific repo where it will get the right attention. Thanks again!

**Comment by alexgordonpandera** [comment]
@danoscarmike Has there been any traction on this issue? Have you been able to duplicate this scenario or have seen this elsewhere?

**Comment by danoscarmike** [comment]
@crwilcox could you assign this one? Thanks!

**Comment by tseaver** [comment]
@alexgordonpandera Can you please show the code (redacting any secrets, if needed) for your `get_client_table` and `close_client` functions?  My suspicion is that you may be leaking resources associated with the client object, rather than the rowset data.

**Comment by alexgordonpandera** [comment]
If the memory leak ceases to exist by removing read_job.consume_all(), what is making you believe that the get_client_table and close_client functions would be leaking resources??

**Comment by tseaver** [comment]
@alexgordonpandera I don't have any evidence, only suspicions based on previous reports where GCF users were leaking client resources.  If you can show the setup / teardown, I can put my suspicions to rest.

The implementation of [`PartialRowsData.consume_all`](https://github.com/googleapis/python-bigtable/blob/ebcdf6c63898d9f98304273c169637f521156884/google/cloud/bigtable/row_data.py#L442-L443) is very straightforward:  for a big enough table, it could certainly exceed a given memory limit, even without a leak (since it copies row data into memory).  You could try iterating over the rowdata object yourself to test whether copying is the problem, e.g.:

```python
    read_job = bt_table.read_rows(row_set=row_set)

    counter = 0
    for row in read_job:
        counter += 1

    read_job.cancel()
    close_client(client)
```

**Comment by tseaver** [comment]
Please feel free to re-open / follow up if you can provide the requested information.
