### ISSUE TITLE
<_MultiThreadedRendezvous of RPC that terminated with status = StatusCode.ABORTE

### ISSUE THREAD

**Issue by TimurTarasenko** [googleapis/python-bigtable#571]
I use Airflow and Google Bigtable.

I'm getting this issue when I try to run code in Airflow.

ERROR - <_MultiThreadedRendezvous of RPC that terminated with
status = StatusCode.ABORTE
details = "Error while reading table 'projects/myproject/instances/dev-02/tables/mytable' : Response was not consumed in time; terminating connection.(Possible causes: slow client data read or network problems)
debug_error_string = "{"created":"@1649868116.434085656","description":"Error received from peer ipv4:142.251.6.95:443","file":"src/core/lib/surface/call.cc","file_line":1061,"grpc_message":"Error while reading table 'projects/myproject/instances/dev-02/tables/mytable' : Response was not consumed in time; terminating connection.(Possible causes: slow client data read or network problems)","grpc_status":10}

Traceback (most recent call last)
File "/usr/local/lib/airflow/airflow/models/taskinstance.py", line 980, in _run_raw_tas
result = task_copy.execute(context=context
File "/home/airflow/gcs/plugins/minutebardata.py", line 55, in execut
tk.get_data(dt=self.dt
File "/home/airflow/gcs/plugins/scraper/ticker.py", line 46, in get_dat
df0 = self.dbhook._load_minubebar_tickers(ticker, start_dt, dtf
File "/home/airflow/gcs/plugins/scraper/db_wrapper.py", line 568, in _load_minubebar_ticker
dfs = [self.process(row, ticker) for row in rows if row is not None
File "/home/airflow/gcs/plugins/scraper/db_wrapper.py", line 568, in <listcomp
dfs = [self.process(row, ticker) for row in rows if row is not None
File "/opt/python3.6/lib/python3.6/site-packages/google/cloud/bigtable/row_data.py", line 485, in _iter
response = self._read_next_response(
File "/opt/python3.6/lib/python3.6/site-packages/google/cloud/bigtable/row_data.py", line 474, in _read_next_respons
return self.retry(self._read_next, on_error=self._on_error)(
File "/opt/python3.6/lib/python3.6/site-packages/google/api_core/retry.py", line 286, in retry_wrapped_fun
on_error=on_error
File "/opt/python3.6/lib/python3.6/site-packages/google/api_core/retry.py", line 184, in retry_targe
return target(
File "/opt/python3.6/lib/python3.6/site-packages/google/cloud/bigtable/row_data.py", line 470, in _read_nex
return six.next(self.response_iterator
File "/opt/python3.6/lib/python3.6/site-packages/grpc/_channel.py", line 416, in _next
return self._next(
File "/opt/python3.6/lib/python3.6/site-packages/grpc/_channel.py", line 803, in _nex
raise sel
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with
status = StatusCode.ABORTE
details = "Error while reading table 'projects/myproject/instances/dev-02/tables/mytable' : Response was not consumed in time; terminating connection.(Possible causes: slow client data read or network problems)
debug_error_string = "{"created":"@1649868116.434085656","description":"Error received from peer ipv4:142.251.6.95:443","file":"src/core/lib/surface/call.cc","file_line":1061,"grpc_message":"Error while reading table 'projects/myproject/instances/dev-02/tables/mytable' : Response was not consumed in time; terminating connection.(Possible causes: slow client data read or network problems)","grpc_status":10}

I use the following approach

    row_set = RowSet()
    row_set.add_row_range_from_keys(
        start_key=ticker + b"#" + startdt,
        end_key=ticker + b"#" + enddt)

    rows = table.read_rows(
        row_set=row_set)
This code works properly when I run this locally. Could you give me any hints to find the solution?

**Comment by meredithslota** [comment]
I was searching for clues here and came across another posting of yours — just confirming that you're using composer-1.15.2-airflow-1.10.14? And that version comes with google-cloud-bigtable==1.6.0? (Not sure if you upgraded since the StackOverflow posted.)

If so, can you try again with a supported version of Composer? That version is no longer within the full support window and I'm wondering if this issue might be mitigated in newer versions. https://cloud.google.com/composer/docs/concepts/versioning/composer-versions

**Comment by meredithslota** [comment]
@Mariatta, if you need someone to help you with the Composer pieces, please reach out to @leahecole.

**Comment by leahecole** [comment]
Ugh, sorry we're dealing with this - these can be hard to trace to figure out where the problem could be. I'd love to know more about the use case and have a few questions -

- Clarifying - you are using Composer version 2.2.3? I'd love to know more about your environment - things like if it's private IP/public IP, any additional packages you have installed
- if you're not and you're self managing it, let us know what you can about the environment
- Are you using one of the Bigtable operators? If so, which one?
- Are you using the KubernetesPodOperator or the GKEStartPodOperator and running the code snippet you shared in a container? If so, let us know which of those two you're using
- Are you using the PythonOperator to run that code snippet directly?
- is the Bigtable instance in the same project that Composer (or Airflow) is?


Thank you!
