### ISSUE TITLE
Upgrade to protobuf version 4?

### ISSUE THREAD

**Issue by katylava** [googleapis/python-bigtable#617]
I'm using another library that pins protobuf at the latest version (4.21.4), and I can't use this library with it because it pins it at <4.

https://github.com/googleapis/python-bigtable/blob/main/setup.py#L36

Are there plans to upgrade soon?

**Comment by Mariatta** [comment]
Hi @katylava, 
There is currently a bug in protobuf 4 that makes it incompatible with our library. We're in touch with the protobuf team about the issue and we're waiting for the next protobuf release to see if things are fixed from their side.

**Comment by Mariatta** [comment]
Protobuf 4 is now compatible with our library. Please upgrade to v 2.11.1 or up. 

Thanks.
