### ISSUE TITLE
v3: replace dicts with protos

### ISSUE THREAD

**Issue by daniel-sanche** [googleapis/python-bigtable#779]
There are some places in the v3 API surface where we are using dicts as the canonical representation for data ([example](https://github.com/daniel-sanche/python-bigtable/blob/3921093359be4de47322e4667486742fb24e11d3/google/cloud/bigtable/_read_rows.py#L72)). Dicts make it easier for users to pass in configuration without constructing custom objects, but they make it harder to properly verify types and make assertions about the state of the request

Before release, we should do a pass through the code to see if there are any places where protos would be a better fit than dicts.

We should also consider whether unstructured dicts should be accepted in the a public API surface (as is standard for GCP libraries), or if we should lean more towards type safety for python-bigtable

**Comment by mutianf** [comment]
Estimate: 2 days

**Comment by daniel-sanche** [comment]
I went through the files and found dict requests in the following places:

- [ ] mutate_row
- [ ] check_and_mutate
- [ ] read_modify_write
- [ ] MutateRowsOperationAsync
