### ISSUE TITLE
Bigtable: plumb 'transport's through from 'Client' to GAPIC generated clients

### ISSUE THREAD

**Issue by tseaver** [googleapis/python-bigtable#8]
/cc @sduskis 

Two issues:

- `bigtable.client.Client.__init__` takes a `channel` argument, but [does nothing with it](https://github.com/googleapis/google-cloud-python/blob/910846426428f24ad49e1a0f716e5bf103b3e3af/bigtable/google/cloud/bigtable/client.py#L102-L114):  the `_channel` attribute is never used.

- The current GAPIC-generated clients still accept a `channel` argument, but are deprecating it in favor of the `transport` argument, where the `transport` is a generated wrapper around the `channel`, providing the method stubs needed to support the API surface.

We should deprecate the `channel` argument to `bigtable.client.Client.__init__`, and add a new `transport` argument.  If passed, the `transport` argument should be forwarded through to the three GAPIC-generated clients.  If `channel` is passed, we should forward it through as well, until the GAPIC-generated code no longer supports it.

**Comment by tseaver** [comment]
Rather than trying to juggle the three transport objects from client instantiation through to the point where the `table_data_client` / `table_admin_client` / `instance_admin_client` properties are first invoked, ISTM that we would do better just to make those properties settable.  Users who wanted to customize the transport would then do:

```python
from google.cloud.bigtable import Client
from google.cloud.bigtable_v2.gapic.bigtable_client import BigtableClient
from google.cloud.bigtable_v2.gapic.transports.bigtable_grpc_transport import BigtableGrpcTransport

client = Client(...)
transport = BigtableGrpcTransport(...)
table_data_client = BigtableClient(transport=transport)
client.table_data_client = table_data_client
```

@crwilcox, @kolea2 WDYT?

**Comment by crwilcox** [comment]
This seems to resemble other library designs for transport override. 

Note that @kolea2 is working on the migration to a new generator though, and most of the imports mentioned above are moving
