### ISSUE TITLE
Support timeout / retry on Table.read_row()

### ISSUE THREAD

**Issue by mwarkentin** [googleapis/python-bigtable#941]
**Is your feature request related to a problem? Please describe.**

We recently experienced an issue where a small number of requests to BigTable using [Table.read_row()](https://cloud.google.com/python/docs/reference/bigtable/latest/google.cloud.bigtable.table.Table#google_cloud_bigtable_table_Table_read_row) hung until we hit the default 60s timeout. This caused issues with our application including the kafka consumer being kicked out of the consumer group after not responding for 30s.

We want to set a more aggressive timeout for this function call (eg. less than 30 seconds) however we haven't been able to figure out a way - `read_row()` does not seem to support either `timeout` or `retry` args which are the documented ways to set a timeout on a request.

 **Describe the solution you'd like**

Support `table.read_row("keyid", timeout=5)`

Alternatively, support setting a new global default timeout via environment variable or config file.

 **Describe alternatives you've considered**

Perhaps we could refactor our code to use `read_rows()` instead and fetch a single row, but this feels hacky.

 **Additional context**

* Existing support issue: https://console.cloud.google.com/support/cases/detail/v2/49879020
* Google account team members: Jason Shin, Scott La Rue

**Comment by mwarkentin** [comment]
@daniel-sanche @ayubun looks like this was tackled in https://github.com/googleapis/python-bigtable/pull/982 (THANKS!!)

Should I close this issue now? (I haven't had a chance to validate the update yet though)

**Comment by mwarkentin** [comment]
Ah, I see that release is not actually available yet. Will wait to confirm. :)

**Comment by daniel-sanche** [comment]
I just cut the release for `v2.27.0`, so I think we should be able to close this. Thanks!
